### ISSUE TITLE
delete_env.sh removes homedir without confirmation

### ISSUE THREAD

**Issue by cucabarra** [Mirantis/mos-tempest-runner#22]
For now, **delete_env.sh** makes _"rm -rf /home/${user_name}/"_ without any confirmation. Thanks to this I lost Tempest reports, when accidentally mis-pressed Enter in MidnightCommander. It would be more safer to have confirmation of deleting homedir (containing prepared venv, Tempest reports, etc)

**Comment by TimurNurlygayanov** [comment]
Hello,

could you please prepare the pull request with the fix, I will merge it.

Thank you!

**Comment by cucabarra** [comment]
A little bit later (maybe tomorrow), OK?

**Comment by TimurNurlygayanov** [comment]
Fixed in https://github.com/Mirantis/mos-tempest-runner/pull/23

Thank you!
